# Generated by Django 4.2.6 on 2023-11-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_tc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtractedData',
        ),
        migrations.DeleteModel(
            name='UserResume',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
